### ISSUE TITLE
Screens of the app

### ISSUE THREAD

**Issue by Fenntasy** [karakuri-js/karakuri#1]
Setting drawer view, with a logout/switch user button in front of the user name. The browser directory, the favorites and the history:

![](https://snag.gy/USnPwb.jpg)

The report view after we clicked on the warning sign in the currently playing part.
![](https://snag.gy/5PkAVo.jpg)

The main view (browse) with a list of tabs that represents all directory.
Can navigate between them by swiping or by clicking on the tabs
![](https://snag.gy/AaVDt3.jpg)

Opening a group of karaoke, with an icon to see the song view
![](https://snag.gy/tWXxlg.jpg)

The song view, displaying the video, a button to favorite or report and the lyrics.
Idea: taping on a line in the lyrics could report the song with that line 
![](https://snag.gy/Yy4VnH.jpg)

**Comment by codeheroics** [comment]
@Fenntasy I just put all this in a README.md, shoud we close this ?

**Comment by codeheroics** [comment]
(The idea was for me to be able to get this without needing to go on GitHub, but I think it makes sense that the README describes the future project anyway)

**Comment by Fenntasy** [comment]
I agree :)
